version: "3"

volumes:
  database:
    driver: local

services:
  postgres:
    image: postgres:16
    container_name: turborepo_postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: turborepo
      POSTGRES_USER: turborepo_user
      POSTGRES_PASSWORD: turborepo_pass
    volumes:
      - database:/var/lib/postgresql/data
